before_script:
  - whoami

stages:
  - deploy

variables:
  DEPLOY_TARGET: "new.briankintz.com"

deploy:
  script:
    - sudo apt-get update -qq && sudo apt-get install -y nodejs
    - sudo npm install -g npm@latest
    - sudo npm install -g grunt-cli
    - npm install
    - grunt build
    - mkdir site
    - cp -r index.html 404.html res/ site/
    - scp -r site/* root@$DEPLOY_TARGET:/var/www/briankintz.com/
  stage: deploy
  only:
    - master
  artifacts:
    paths:
      - site/